### ISSUE TITLE
VST3NetReceive?

### ISSUE THREAD

**Issue by nippoo** [vgorloff/VST3NetSend#15]
Hey there! Fantastic work on this plugin.

I was wondering whether you had any plans or ideas to implement the receive-side of this.

Essentially I'm trying to have an insert (send/receive) plugin combined so a single plugin could be used to pipe audio between other apps / computers that don't support ReWire or a standard interface for doing so.

I don't think such a thing exists (ideally as an AU so it can run in QLab) but correct me if I'm wrong!

**Comment by vgorloff** [comment]
`VST3NetSend` plugin is just a VST3 wrapper on top of AU plugin. Making `VST3NetReceive` theoretically should be the similar thing – another VST3 wrapper.

Will think of preparing kind of draft in upcoming months.

How about SoundFlower to wire music apps?

- https://rogueamoeba.com/freebies/soundflower/
- https://github.com/mattingalls/Soundflower/releases
