### ISSUE TITLE
Is there a compiled Binary available (ie VST3NetSend.dll)?

### ISSUE THREAD

**Issue by Godlike-Productions** [vgorloff/VST3NetSend#17]
The link in the readme for the binary, just takes you to the release with the source code.  Is there a compiled dll available, or do we need to compile it ourselves?

I'm looking for an alternative to ReaStream that supports both Windows and Mac, and thought this might be the solution.

**Comment by vgorloff** [comment]
The `dll` is a Windows OS thing.
This plugin uses Apple-specific infrastructure for transmitting Audio :)
