### ISSUE TITLE
Hello Vlad

### ISSUE THREAD

**Issue by Mistahbrock** [vgorloff/VST3NetSend#18]
I just compiled this project on OS X 10.15 - Catalina with Xcode 12.3

In the VST3_SDK 3.7.1 there is some changes so at least two files needed to be renamed

the file named "pluginfactoryvst3.cpp" is now named "pluginfactory.cpp"
#include "public.sdk/source/main/pluginfactory.cpp"

And I added the line 
#include "public.sdk/source/common/commoniids.cpp" in your VST3SDK.cpp

Now it compiles without error :)

Besides form this I also changed the line
"Steinberg::Vst::PlugType::kFxTool..." to "Steinberg::Vst::PlugType::kFxNetwork..." as it makes more sense to me
 
Happy new year

**Comment by vgorloff** [comment]
Thank you!
All issues corrected in Release 1.0.19 - https://github.com/vgorloff/VST3NetSend/releases/tag/1.0.19
